### ISSUE TITLE
Return respone header with the data 

### ISSUE THREAD

**Issue by omarkhatibco** [cool-hooks/react-wordpress-hooks#108]
Hi,

Some of WP Endpoint send some data in response header such as `X-WP-Total` & `X-WP-TotalPages`,

so it would be great if your return the response header with that returned data.

Thanks!

**Comment by JB1905** [comment]
In v3.2.0 I will add headers, status & statusText to returned values 🙂

**Comment by omarkhatibco** [comment]
@JB1905 thanks!
